export const words: string[] = [
  "Encryption",
  "Firewall",
  "Hacker",
  "Malware",
  "Phishing",
  "Cyberattack",
  "Cybersecurity",
  "Authentication",
  "Biometrics",
  "Vulnerability",
  "Patch",
  "Password",
  "Identity",
  "Data breach",
  "Cybercrime",
  "Ransomware",
  "Endpoint security",
  "Network security",
  "Intrusion detection",
  "Cyber hygiene",
  "Zero-day",
  "Social engineering",
  "Two-factor authentication",
  "Cyberwarfare",
  "Information security",
  "Cyber resilience",
  "Threat intelligence",
  "Sandboxing",
  "Penetration testing",
  "Access control",
  "Security audit",
  "Digital forensics",
  "Incident response",
  "Security policy",
  "Cyber insurance",
  "Secure coding",
  "Data encryption",
  "Secure socket layer (SSL)",
  "Virtual private network (VPN)",
  "Multi-factor authentication",
  "Secure shell (SSH)",
  "Denial-of-service (DoS)",
  "Distributed denial-of-service (DDoS)",
  "Security architecture",
  "Intrusion prevention system (IPS)",
  "Security awareness",
  "Risk assessment",
  "Cybersecurity framework",
  "Threat modeling",
];
