import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const ppNeue = localFont({ src: "../../public/fonts/ppneue.woff2" });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rhivet Network",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ppNeue.className}>{children}</body>
    </html>
  );
}
